import { App, arrayBufferToBase64, Component, FileSystemAdapter, MarkdownRenderer, Notice, Platform, TFile } from "obsidian";
import { Markdown2HtmlSettings } from "settings";
import CopyInProgressModal from "ui/copy-modal";
import { isEmpty, Log, removeEmptyLines } from "utils/helper";

export interface CopyCommand {
  startCopy(content: Promise<string>): Promise<void>;
  copyToClipboard(settings: Markdown2HtmlSettings): Promise<void>;
  inProgress: boolean;
}

export default class CopyHtml implements CopyCommand {
  protected app: App;
  protected modal: CopyInProgressModal;

  protected htmlRoot: HTMLDivElement = window.createDiv();
  private copyComponent = new Component();
  private _inProgress: boolean = false;

  constructor(app: App) {
    this.app = app;
    this.modal = new CopyInProgressModal(app);
    this.copyComponent.load();
  }

  /** triggers the render of the markdown note or selection. */
  async startCopy(content: Promise<string>): Promise<void> {
    try {
      this.init();
      const path = this.app.workspace.activeEditor?.file?.path ?? "";
      void MarkdownRenderer.render(this.app, await content, this.htmlRoot, path, this.copyComponent);
    } catch (e) {
      Log.e("Error while rendering HTML", e);
      new Notice("Error while rendering HTML", 3500);
      this.finish();
    }
  }

  /**
   * Cleans up the rendered HTML and stores it in the system clipboard.
   * Executes after a short delay to make sure all steps of the rendering are done.
   * Each time the method is called within the delay, the timer resets.
   */
  async copyToClipboard(settings: Markdown2HtmlSettings): Promise<void> {
    if (this.inProgress) {
      Log.d("Rendering finished, cleaning HTML...");
      const data = await this.cleanHtml(settings);
      Log.d("Copying HTML to clipboard...");
      let clipboardWrite: Promise<void>;
      if (Platform.isDesktopApp) {
        const item = new ClipboardItem({
          "text/plain": new Blob([data], { type: "text/plain" }),
          "text/html": new Blob([data], { type: "text/html" }),
        });
        clipboardWrite = navigator.clipboard.write([item]);
      } else {
        // mobile obsidian can't do the fancy stuff with html mime type
        clipboardWrite = navigator.clipboard.writeText(data);
      }
      clipboardWrite
        .then(() => new Notice("HTML copied to the clipboard", 3500))
        .catch(e => {
          Log.e("Error while copying HTML to the clipboard", e);
          new Notice("Couldn't copy HTML to the clipboard", 3500);
        })
        .finally(() => this.finish());
    }
  }

  get inProgress(): boolean {
    return this._inProgress;
  }

  private init() {
    Log.d("Starting copy process...");
    this._inProgress = true;
    this.modal.open();
  }

  protected finish() {
    this._inProgress = false;
    this.htmlRoot.empty();
    this.modal.close();
    Log.d("Copy process finished.");
  }

  /**
   * runs a few steps to clean the HTML generated by Obsidian's internal markdown renderer.
   *
   * @param settings the settings of the plugin
   */
  private async cleanHtml(settings: Markdown2HtmlSettings) {
    if (settings.cleanup) {
      this.removeFrontmatter(settings);
      this.removeAttributes(settings);
      this.removeEmptyContainer(settings);
    }
    await this.convertImages();

    const html = removeEmptyLines(this.htmlRoot.innerHTML);
    return html;
  }

  /** Remove frontmatter header */
  protected removeFrontmatter(settings: Markdown2HtmlSettings) {
    if (settings.removeFrontmatter) {
      const frontmatterNodes = this.htmlRoot.querySelectorAll(".frontmatter, .frontmatter-container");
      frontmatterNodes.forEach(node => node.remove());
    }
  }

  /** remove all child nodes that don't have any content (removes empty paragraphs left by comments) */
  private removeEmptyContainer(settings: Markdown2HtmlSettings) {
    if (settings.removeEmptyContainer) {
      this.htmlRoot.querySelectorAll("p, div").forEach(node => {
        if (isEmpty(node.innerHTML)) {
          node.remove();
        }
      });
    }
  }

  /** Remove all irrelevant attributes of elements */
  private removeAttributes(settings: Markdown2HtmlSettings) {
    const elements = this.htmlRoot.querySelectorAll<HTMLElement>("*");

    elements.forEach(element => {
      if (element.closest('svg') && element.tagName.toLowerCase() === 'svg') {
        return;
      }
      const attributesToRemove: string[] = [];
      const classesToKeep: string[] = Object.assign([], settings.classList).filter(cls =>
        element.classList.contains(cls)
      );

      const attributes = element.attributes;
      for (let i = 0; i < attributes.length; i++) {
        const attribute = attributes[i];
        if (!attribute || typeof attribute.name !== "string") {
          continue;
        }
        const attrName = attribute.name.toLowerCase();
        if (!settings.attributeList.contains(attrName)) {
          attributesToRemove.push(attrName);
        }
      }
      // remove all attributes that are not allowed
      attributesToRemove.forEach(attr => element.removeAttribute(attr));
      // readd classes to keep
      element.addClasses(classesToKeep);
    });
  }

  /** Convert internal Images to base64 data URL */
  private async convertImages() {
    const images: NodeListOf<HTMLImageElement> = this.htmlRoot.querySelectorAll('img:not([src^="http"])');
    for (let i = 0; i < images.length; i++) {
      const image = images[i];
      if (!image || typeof image.src !== "string") {
        continue;
      }
      image.src = await this.toBase64(image.src);
    }
  }

  /** Read a file from an uri and turn it into a base64 string */
  private async toBase64(src: string): Promise<string> {
    if (src.startsWith("data:")) {
      return src;
    }

    try {
      const adapter = this.app.vault.adapter;
      if (adapter instanceof FileSystemAdapter) {
        const basePath = adapter.getBasePath();
        const basePathStart = src.indexOf(basePath);
        const localPath = decodeURI(src.slice(basePathStart + basePath.length, src.lastIndexOf("?")));
        const file = this.app.vault.getFileByPath(localPath);
        if (!file) {
          throw new Error(`File not found in vault: ${localPath}`);
        }
        const fileData = await adapter.readBinary(file.path);
        const dataUrl = `data:${this.getMimeType(file)};base64,${arrayBufferToBase64(fileData)}`;

        if (dataUrl.length > 1024 * 128) { // if the image is larger than 128KB, it's probably better to keep it as a file link instead of embedding it as base64
          Log.w(`Image too large (${dataUrl.length} bytes) to embed as base64, using file://`);
          return `file://${adapter.getFullPath(file.path)}`;
        }

        return dataUrl;

      } else {
        throw new Error("Unsupported vault adapter for reading binary data");
      }
    } catch (e) {
      Log.e(`Error while converting image to base64: ${src}`, e);
      return src; // fallback to original src if conversion fails
    }
  }

  private getMimeType(file: TFile): string {
    switch (file.extension) {
      case "png":
        return "image/png";
      case "jpg":
      case "jpeg":
        return "image/jpeg";
      case "gif":
        return "image/gif";
      case "webp":
        return "image/webp";
      case "svg":
        return "image/svg+xml";
      case "bmp":
        return "image/bmp";
      default:
        return "image/unknown";
    }
  }
}
